name: Azure Initial Setup

on:
  push:
    branches: [ main ]

# Set environment variables for terraform
env:
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}

# Jobs to run
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.4

    - name: Terraform Init global_infra
      run: terraform init
      working-directory: ./terraform/global_infra

    - name: Terraform Apply global_infra
      run: terraform apply -auto-approve
      working-directory: ./terraform/global_infra

    - name: Logout of Azure
      run: az logout